services:
  python:
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    image: research-template-python
    container_name: research-template-python
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true

  r:
    build:
      context: .
      dockerfile: docker/r/Dockerfile
    image: research-template-r
    container_name: research-template-r
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true

  tex:
    build:
      context: .
      dockerfile: docker/tex/Dockerfile
    image: research-template-tex
    container_name: research-template-tex
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true
